apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: tailcar-validator
webhooks:
- name: tailnet.tailcar.rajsingh.info
  clientConfig:
    service:
      name: tailcar-webhook
      namespace: tailcar-system
      path: /validate-tailcar-rajsingh-info-v1alpha1-tailnet
      port: 443
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1"]
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["tailcar.rajsingh.info"]
    apiVersions: ["v1alpha1"]
    resources: ["tailnets"]
    scope: "*"
