apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  namespace: default
  annotations:
    tailcar.rajsingh.info/inject: "true"
    tailcar.rajsingh.info/tailnet: "test-tailnet"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80